# Generated by Django 5.1.4 on 2024-12-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="donation_images/"
            ),
        ),
    ]
