# Generated by Django 5.1.4 on 2024-12-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_donation_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="location",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="location",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="location",
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(default="0,0", max_length=255),
            preserve_default=False,
        ),
    ]
