# Generated by Django 5.1.4 on 2024-12-11 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_remove_donor_location_remove_recipient_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
