# Generated by Django 5.1.4 on 2025-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_donation_deleted_at_donation_reserved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
