# Generated by Django 5.1.4 on 2025-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0007_donation_self_pickup_volunteerrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="is_in_transit",
            field=models.BooleanField(default=False),
        ),
    ]
